### PR TITLE
Embedding Images and videos

### PR DESCRIPTION
**Pull request by aaronsekisambu**
### Description
- This is a simple project about embedded videos and images

### How to test manually
- Clone the repo 
- Run the [index.html](https://github.com/aaronsekisambu/my-personal-projects/blob/master/index.html) page

### CODE REVIEW

**Review by stratospherique — COMMENTED** [review]
### Pull request under review by Ahmed Mahfoudh TSE

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work :clap: . However, you need to make the following changes in order to get approval for your project. check below :arrow_down: 
image
- Your page have an **horizontal scroll** problem, kindly fix it :pray: 

##### Sidebar Recommended videos

* [ ] It shows the recommended video's thumbnail preview
> Use image instead of inserting a video element

* [ ] Check HTML markup with this [validator](https://validator.w3.org/)#validate_by_upload.
* [ ] add info to your readme file to make it more descriptive(e.g project's description, link to assignment, link to you github profile, live link preview etc..)

### That's it :relaxed: . When finished, kindly resubmit another code review request :pray:

**Review by Redvanisation — CHANGES_REQUESTED** [review]
### Hello @aaronsekisambu and @alvp01 

**Nice work on this project 👍However we still need to address the changes bellow:** ⬇️ 

- You have to set up stickler to lint the CSS code, to find out more out how to do that check out this [link](https://github.com/microverseinc/linters-config/tree/master/css) 

### _After making the required changes please submit a new code review request_

### Good luck guys! 🍀

**Comment by aaronsekisambu** [comment]
@Redvanisation Thanks for the comment, however, we enabled stickler on the master branch. We also used eslint configs to lint our code prior to pushing it to git hub

**Review by maelfosso — APPROVED** [review]
# Good job :+1: 

**You can merge !!!**
Good luck with the next project
Don't forget to fill the project completion form.

**Pull request merged**
